//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMillionare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public string Answer1 { get; set; }
        public byte Validity { get; set; }
        public int Id { get; set; }
        public int QId { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
